apiVersion: v1
kind: Application
runtimeId: 01J9C694269APB2TCNAG9CJYVC
applicationId: 01JAFW10F5VD3JY0254HWP0M4T
applicationName: cloud-apps-demo
action: DEPLOY
containerPort: 8080
healthCheckPath: /healthz
imageUrl: 185072717495.dkr.ecr.sa-east-1.amazonaws.com/cloud-apps-demo
tag: latest
mem: 8
cpu: 8
replicaNum:
  min: 1
  max: 3
envVars:
  - key: ENV_FROM_ACTION
    value: value1
secretVars:
  - key: SECRET_FROM_ACTION
    value: secret_value1
