apiVersion: platform.cloud.stackspot.com/v1alpha1
kind: ApplicationDeployment
metadata:
  appVersion: 1.0.0
  name: app-demo-prd
  tags:
    - name: stk-tenant-test
      value: stk-tenant-test
  labels:
    - name: tenant-label
      value: stk-tenant-test
  stackspot:
    applicationId: 01JAFW10F5VD3JY0254HWP0M4T
    workspaceId: 01JAFW10F5VD3JY0254HWP0M4T
spec:
  runtimeId: 01JQC2Y5M984NH9T13HZN9M4FZ
  deployTemplate: "default_stackspot_application:v1"
  deployTemplateValues:
    image:
      repository: "742799255367.dkr.ecr.sa-east-1.amazonaws.com/cloud-apps-demo"
      tag: latest    
    service:
      port: 80
      type: ClusterIP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 100m
        memory: 1024Mi
    env:
      - name: EXAMPLE_KEY
        value: "example value"
      - name: EXAMPLE_SECRET
        valueFrom:
          secretKeyRef:
            name: example-secret
            key: example-key