apiVersion: platform.cloud.stackspot.com/v1alpha2
kind: ApplicationDeployment
metadata:
  version: 1.0.0
  name: app-demo-2
spec:
  applicationId: 01JQA7AYKT86J6NFB1A6AF7GUY
  runtimeId: 01JQBTZDC22C0QYC2N294SA4K9
  deployTemplate: "default_stackspot_application_chart:0.1.1"
  deployTemplateValues:
    image:
      repository: IMAGE_REPOSITORY
      tag: IMAGE_TAG
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80     
    service:
      port: 80
      type: ClusterIP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 100m
        memory: 1024Mi
    env:
      - name: ENV_NAME
        value: "ENV_VALUE"