apiVersion: v1
kind: Application
metadata:
  id: 01JAFW10F5VD3JY0254HWP0M4T
  name: cloud-apps-demo
spec:
  runtime:
    id: 01J9C694269APB2TCNAG9CJYVC
    name: Runtime 1
    memory: 8
    cpu: 8
    replicaNum:
      min: 2
      max: 10
      cpu: 8
  container:
    imageUrl: 742799255367.dkr.ecr.sa-east-1.amazonaws.com/cloud-apps-demo
    port: 8080
    healthCheckPath: /healthz
    envVars:
      - key: ENV_VAR_DEMO1
        value: value1
      - key: ENV_VAR_DEMO2
        value: value2
      - key: ENV_VAR_DEMO3
        value: value3