name: Cloud Deploy Action Test STG

on:
  push:
    branches:
        - feat/1/action-stg
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.imageTag}}
    steps:
      - name: Build process generating a tag
        id: tag
        run: echo "imageTag=demo1" >> $GITHUB_OUTPUT

  deploy:
    runs-on: engineering-runners-stg
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.1
      - name: Deploy repo application
        uses: stack-spot/cloud-deploy-action@feat/1/action-stg
        id: deploy
        with:
          CLIENT_REALM: ${{ secrets.CLIENT_REALM_STG }}
          CLIENT_ID: ${{ secrets.CLIENT_ID_STG }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY_STG }}
          APPLICATION_FILE: ${{ github.workspace }}/.stk/application-stg.yaml
          IMAGE_TAG: ${{needs.build.outputs.tag}}
          VERBOSE: true
 