name: Deploy STG

on:
    push:
        branches:
           - feat/1/action-stg
    workflow_dispatch:
  
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            tag: ${{ steps.tag.outputs.imageTag}}
        steps:
            - name: Build process generating a tag
              id: tag
              run: echo "imageTag=latest" >> $GITHUB_OUTPUT
    
    deploy:
        needs: [build]
        uses: stack-spot/cloud-deploy-action/.github/workflows/reusable-deploy.yaml@feat/1/action-stg
        secrets:
            CLIENT_REALM: ${{ secrets.CLIENT_REALM_STG }}
            CLIENT_ID: ${{ secrets.CLIENT_ID_STG }}
            CLIENT_KEY: ${{ secrets.CLIENT_KEY_STG }}
        with:
            APPLICATION_FILE: ${{ github.workspace }}/stackspot/application-stg.yaml
            IMAGE_TAG: ${{needs.build.outputs.tag}}