name: Cloud Deploy Action Test STG

on:
  push:
    branches:
        - feat/1/action-stg
  workflow_dispatch:

jobs:
  deploy:
    runs-on: engineering-runners-stg
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy repo application
        uses: stack-spot/cloud-deploy-action@feat/1/action-stg
        id: deploy
        with:
          CLIENT_REALM: ${{ secrets.CLIENT_REALM_STG }}
          CLIENT_ID: ${{ secrets.CLIENT_ID_STG }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY_STG }}
          APPLICATION_FILE: ${{ github.workspace }}/.stk/application.yaml
          IMAGE_TAG: demo1
          VERBOSE: true
 